// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCjTLlBcQu05aYfMrcMgPq0PeE4I0Td1kw',
    appId: '1:682071905288:web:b83a4af57c84ecc17a6dbd',
    messagingSenderId: '682071905288',
    projectId: 'todo-app-61c59',
    authDomain: 'todo-app-61c59.firebaseapp.com',
    storageBucket: 'todo-app-61c59.firebasestorage.app',
    measurementId: 'G-3JC5Y8MEGY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQnye8MdcxgnBYlLSfWaXA1rDd4UTD7M8',
    appId: '1:682071905288:android:648a6e0e36fbbab27a6dbd',
    messagingSenderId: '682071905288',
    projectId: 'todo-app-61c59',
    storageBucket: 'todo-app-61c59.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDPkvJY_Mxiih2Y0uluaoxX39r9JNGD4Qg',
    appId: '1:682071905288:ios:75d093088a80ec2c7a6dbd',
    messagingSenderId: '682071905288',
    projectId: 'todo-app-61c59',
    storageBucket: 'todo-app-61c59.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDPkvJY_Mxiih2Y0uluaoxX39r9JNGD4Qg',
    appId: '1:682071905288:ios:75d093088a80ec2c7a6dbd',
    messagingSenderId: '682071905288',
    projectId: 'todo-app-61c59',
    storageBucket: 'todo-app-61c59.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCjTLlBcQu05aYfMrcMgPq0PeE4I0Td1kw',
    appId: '1:682071905288:web:fdcb921c03514f707a6dbd',
    messagingSenderId: '682071905288',
    projectId: 'todo-app-61c59',
    authDomain: 'todo-app-61c59.firebaseapp.com',
    storageBucket: 'todo-app-61c59.firebasestorage.app',
    measurementId: 'G-P29LP07F40',
  );
}
